import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');


  const handleEmail = (e) => {
    setEmail(e.target.value)
  }

  const handlePassword = (e) => {
    setPassword(e.target.value)
  }

  const onLogin = () => {
    if(email == 'admin@midland.com' && password == '1234'){
      alert("Sukses")
    } else {
      alert("Gagal")
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Midland Properti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 style={{textAlign:'center'}}>Admin <br/> Midland Properti</h2>

        <div className={styles.sizing}>
          <form>
            <div>
              <label>Email :</label>
              <input type={"email"} onChange={handleEmail} placeholder='example@domain.com' className='form-control' />
            </div>

            <div style={{paddingTop:10}}>
              <label>Password :</label>
              <input type={"password"} onChange={handlePassword} placeholder='*******' className='form-control' />
            </div>

            <div style={{paddingTop:10}}>
              <button onClick={onLogin} className={'btn btn-outline-primary ' + styles.fullbtn} type='submit'>
                Masuk
              </button>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}
