import Head from 'next/head'
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { Component, useState } from 'react'
import { logo } from '../assets';
import styles from '../styles/Home.module.css'

export default function Home(props) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLogin, setIsLogin] = useState(false);

  const handleEmail = (e) => {
    setEmail(e.target.value)
  }

  const handlePassword = (e) => {
    setPassword(e.target.value)
  }

  const router = useRouter();

  const onLogin = () => {
    if (email == 'admin@midland.com' && password == '12345678') {
      alert("Sukses");
      router.push('/dashboard')
    } else {
      alert("Gagal")
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Midland Properti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src={logo} height={100} width={80} />
        <h2 style={{ textAlign: 'center' }}>Midland Properti</h2>

        <div className={styles.sizing}>
          <form>
            <div>
              <label>Email :</label>
              <input type={"email"} value={email} onChange={handleEmail.bind(this)} placeholder='example@domain.com' className='form-control' />
            </div>

            <div style={{ paddingTop: 10 }}>
              <label>Password :</label>
              <input type={"password"} value={password} onChange={handlePassword.bind(this)} placeholder='*******' className='form-control' />
            </div>

            <div style={{ paddingTop: 10 }}>
              <Link href={isLogin == true ? '/dashboard' : '/'}>
                <button className={'btn btn-outline-primary ' + styles.fullbtn} onClick={() => onLogin()}>
                  Masuk
                </button>
              </Link>
            </div>
          </form>
        </div>
      </main>
    </div>
  )
}
